### ISSUE TITLE
Ran quick test as described however results differ from final_g_clusters_to_obtain.txt

### ISSUE THREAD

**Issue by MMicorescu** [kamimrcht/CARNAC#2]
"Command line was: ./CARNAC-LR -f test/test.input -o test/mm.txt
Parsing infile...
preprocessing of the graph
Connected components: 1
Connected Component 0 size 20
Computing pseudo cliques
12 clustering coefficients to check
Computing clusters
Computing clusters
1/12 cutoff 1 cut 48
Computing clusters
2/12 cutoff 0.866667 cut 40
Computing clusters
3/12 cutoff 0.678571 cut 16
4/12 cutoff 0.822222 cut 40
Computing clusters
Computing clusters
5/12 cutoff 0.8 cut 40
6/12 cutoff 0.666667 cut 18
Computing clusters
Computing clusters
7/12 cutoff 0.761905 cut 18
Computing clusters
8/12 cutoff 0.619048 cut 28
Computing clusters
9/12 cutoff 0.690909 cut 18
10/12 cutoff 0.47619 cut 28
Computing clusters
11/12 cutoff 0.428571 cut 0
Done.
ubuntu@ip-10-157-12-61: /home/ubuntu/git/CARNAC$ cd test/
ubuntu@ip-10-157-12-61:/home/ubuntu/git/CARNAC/test$ ls
clusters.list  final_g_clusters_to_obtain.txt  mm.txt  test.input  two_clusters.fasta
ubuntu@ip-10-157-12-61:/home/ubuntu/git/CARNAC/test$ head mm.txt
0 15 11 16 17 6 19 8 1 14 5 2 3 7 10 4 13 18 12 9
ubuntu@ip-10-157-12-61:/home/ubuntu/git/CARNAC/test$ head final_g_clusters_to_obtain.txt
0 1 5 6 11 15 16 17 19
2 3 4 7 8 9 10 12 13 14 18

**Comment by kamimrcht** [comment]
Hi, indeed the tests were deprecated. I plan on having new ones soon.
