### ISSUE TITLE
Release to bioconda?

### ISSUE THREAD

**Issue by zachcp** [kamimrcht/CARNAC#8]
Hi Kamimrcht,

Thanks for this package/work. I recently stumbled accross it and it works great so I would like to package it for [bioconda](https://bioconda.github.io/) which I think will help for inclusion in bioinformatic workflows.  However, bioconda requires that you download code from a stable release. Do you think you could cut a release for the CARNAC-LR package on github? If you do so, I would be happy to package it up.

Thanks,
zach cp

**Comment by npavlovikj** [comment]
I second this request! A tagged release and adding License file would be great.

**Comment by kamimrcht** [comment]
Done! Thank you both for your patience. @zachcp are you still ok to package it ?

**Comment by npavlovikj** [comment]
This is great @kamimrcht  - many thanks for the prompt response!
I already started a bioconda recipe using the commit version, https://github.com/bioconda/bioconda-recipes/pull/16585, so hopefully I will have the OSX build fixed today.
@zachcp , you are more than welcome to add to the recipe if you think something is missing.

**Comment by zachcp** [comment]
thanks @kamimrcht  and @npavlovikj . I can take a look at @npavlovikj 's  bioconda package later today but it looks like its already in good hands!

**Comment by npavlovikj** [comment]
Hi @kamimrcht and @zachcp ,

CARNAC-LR is now available on bioconda, https://anaconda.org/bioconda/carnac-lr, for both Linux and OSX. All python scripts and executables are included in the recipe (as you can see on the link above). Please give it a try, and if you encounter any issues, please feel free to modify the recipe or let me know.
